### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by robinbonnes** [dacoto/larastus-issues#5]
**Describe the bug**
When trying to login it shows the dashboard and then logs out.

**To Reproduce**
1. Go to login
2. Login
3. Get logged out

**Expected behavior**
Stay logged in.

**Additional context**
First I had to add the `SANCTUM_STATEFUL_DOMAINS` parameter to the .env file because it didn't login at all. I think it has something to do with cors/csrf/sanctum.

**Comment by dacoto** [comment]
Please send an email with details and a screenshot to support@dacoto.com 

Thank you.
